#!/bin/bash -l
#SBATCH -p debug
#SBATCH -t 00:10:00
#SBATCH -A mp309
#SBATCH -o openmp24.%j.stdout
#SBATCH -e openmp24.%j.error
#SBATCH -N 1
export OMP_NUM_THREADS = 1
srun -n 1 -c 1 ./a.out
export OMP_NUM_THREADS = 2
srun -n 1 -c 2 ./a.out
export OMP_NUM_THREADS = 3
srun -n 1 -c 3 ./a.out
export OMP_NUM_THREADS = 4
srun -n 1 -c 4 ./a.out
export OMP_NUM_THREADS = 5
srun -n 1 -c 5 ./a.out
export OMP_NUM_THREADS = 6
srun -n 1 -c 6 ./a.out
export OMP_NUM_THREADS = 7
srun -n 1 -c 7 ./a.out
export OMP_NUM_THREADS = 8
srun -n 1 -c 8 ./a.out
export OMP_NUM_THREADS = 9
srun -n 1 -c 9 ./a.out
export OMP_NUM_THREADS = 10
srun -n 1 -c 10 ./a.out
export OMP_NUM_THREADS = 11
srun -n 1 -c 11 ./a.out
export OMP_NUM_THREADS = 12
srun -n 1 -c 12 ./a.out
export OMP_NUM_THREADS = 13
srun -n 1 -c 13 ./a.out
export OMP_NUM_THREADS = 14
srun -n 1 -c 14 ./a.out
export OMP_NUM_THREADS = 15
srun -n 1 -c 15 ./a.out
export OMP_NUM_THREADS = 16
srun -n 1 -c 16 ./a.out
export OMP_NUM_THREADS = 17
srun -n 1 -c 17 ./a.out
export OMP_NUM_THREADS = 18
srun -n 1 -c 18 ./a.out
export OMP_NUM_THREADS = 19
srun -n 1 -c 19 ./a.out
export OMP_NUM_THREADS = 20
srun -n 1 -c 20 ./a.out
export OMP_NUM_THREADS = 21
srun -n 1 -c 21 ./a.out
export OMP_NUM_THREADS = 22
srun -n 1 -c 22 ./a.out
export OMP_NUM_THREADS = 23
srun -n 1 -c 23 ./a.out
export OMP_NUM_THREADS = 24
srun -n 1 -c 24 ./a.out
